name = "kings-league-api"
main = "api/index.js"
compatibility_date = "2023-01-18"

[site]
bucket = "./assets"


[env.production]
vars = { ENVIRONMENT = "production" }
routes = [
  { pattern = "kings-league-api.ing-jcarreno.workers.dev", custom_domain = true }
]
