name: Scrape Kings League Infojobs Website

on:
  workflow_dispatch: # para tener un btn
    
  repository_dispatch: # para poder ejecutarlo desde linea de comando
    type:
      - webhook

  schedule:
    - cron: "0 */1 * * 0"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.3
          run_install: true
      - run: |
          npm run scrape
          git config user.name kings-league-bot
          git add -A
          git commit -m "[bot] Update Kings League database"
          git push origin main
      
